apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
   name: http-app-scaledobject
spec:
   scaleTargetRef:
      name: http-app
   minReplicaCount: 2
   maxReplicaCount: 20
   triggers:
      - type: prometheus
        metadata:
           serverAddress: http://prometheus-operated.monitoring.svc.cluster.local:9090
           threshold: '5'
           query: sum(rate(http_requests_total[1m])) 
