# a cluster with 3 control-planes nodes and 2 worker nodes
# kind create cluster --config cluster.yaml --name 3-m-2-w-cluster
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: control-plane
- role: control-plane
- role: worker
- role: worker
